name: autotag

on:
  push:
    branches: [ "master" ]

jobs:
  tag:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up R 4.0.5
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.5'

      - name: git config
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Crear tag con la ultima version en DESCRIPTION
        run: |
          pattern <- readLines("DESCRIPTION")[[3]]
          version <- gsub("Version: ", "", pattern)
          system(paste0('git tag -f ', version))
          system('git push origin -f --tags')
        shell: Rscript {0}
